elasticsearch:
  endpoint: "https://search-tus-esc-euljuc3vdk47fbng3oxx2ndo4y.eu-west-1.es.amazonaws.com"

aws:
  region: "eu-west-1"
  roleARN: "arn:aws:iam::970382336432:role/Cognito_dwp4552_elasticsearchAuth_Role"

users:
  - max:
      password: I07%0&8bv4$ie!92hr7q6fxs#7wUGO9%jJqV
      backend_roles:
        - backend-role-1
        - backend-role-2